envs:
  DOCKER_USERNAME: no0dles
  IMAGE: no0dles/hammerkit

includes:
  tsc: ./best-practices/build.tsc.yaml
  npm: ./best-practices/build.npm.yaml
  eslint: ./best-practices/build.eslint.yaml
  prettier: ./best-practices/build.prettier.yaml
  docker: ./best-practices/build.docker.yaml
  jest: ./best-practices/build.jest.yaml
  helm: ./best-practices/build.helm.yaml
  gcloud: ./best-practices/build.gcloud.yaml
