envs:
  NODE_VERSION: 14.16.0

tasks:
  install:
    description: install dependencies
    image: node:$NODE_VERSION
    cmds:
      - npm install
    generates:
      - node_modules
    mounts:
      - $PWD/.npm:/.npm
      - $PWD/.config:/.config
    src:
      - package.json
      - package-lock.json

  build:
    description: build typescript
    deps: [install]
    image: node:$NODE_VERSION
    src:
      - src
      - tsconfig.json
    generates:
      - dist
    cmds:
      - node_modules/.bin/tsc

  format:
    description: lint fix and prettier
    image: node:$NODE_VERSION
    deps: [install]
    cmds:
      - node_modules/.bin/prettier -w src/** tests/**
      - node_modules/.bin/eslint . --ext .ts --fix
    src:
      - src
      - tests
      - .eslintignore
      - .eslintrc
      - .prettierrc

  lint:
    description: lint source code
    image: node:$NODE_VERSION
    deps: [install]
    src:
      - src
      - tests
      - .eslintignore
      - .eslintrc
    cmds:
      - node_modules/.bin/eslint . --ext .ts

  prettier:

    image: node:$NODE_VERSION
    deps: [install]
    src:
      - src
      - tests
      - .prettierrc
    cmds:
      - node_modules/.bin/prettier -w src/** tests/**

  test:
    description: test code
    deps: [install]
    src:
      - src
      - tests
      - jest.config.ts
      - tsconfig.test.json
      - tsconfig.json
      - examples
    generates:
      - coverage
    cmds:
      - node_modules/.bin/jest --coverage

  publish:minor:
    description: publish npm package with minor version
    deps: [build]
    cmds:
      - npm version minor
      - npm publish

  publish:patch:
    description: publish npm package with patch version
    deps: [build]
    cmds:
      - npm version patch
      - npm publish
