tasks:
  rebuild:
    description: build typescript
    deps: [ npm:ci ]
    image: node:14.16.0
    src:
      - src
      - tsconfig.json
    generates:
      - dist
    cmds:
      - rm -r dist || true
      - node_modules/.bin/tsc

  build:
    description: build typescript
    deps: [ npm:ci ]
    image: node:14.16.0
    src:
      - src
      - tsconfig.json
    generates:
      - dist
    cmds:
      - node_modules/.bin/tsc

  build:test:
    description: build typescript
    deps: [npm:ci]
    image: node:14.16.0
    src:
      - src
      - tsconfig.json
      - tsconfig.test.json
    generates:
      - dist
    cmds:
      - node_modules/.bin/tsc -p tsconfig.test.json

  format:
    description: lint fix and prettier
    image: node:14.16.0
    deps: [npm:ci]
    cmds:
      - node_modules/.bin/prettier -w src/** tests/**
      - node_modules/.bin/eslint . --ext .ts --fix
    src:
      - src
      - tests
      - .eslintignore
      - .eslintrc
      - .prettierrc

  lint:
    description: lint source code
    image: node:14.16.0
    deps: [npm:ci]
    src:
      - src
      - tests
      - .eslintignore
      - .eslintrc
    cmds:
      - node_modules/.bin/eslint . --ext .ts

  prettier:
    description: format source code
    image: node:14.16.0
    deps: [npm:ci]
    src:
      - src
      - tests
      - .prettierrc
    cmds:
      - node_modules/.bin/prettier -w src/** tests/**

  test:
    description: test code
    deps: [npm:ci]
    src:
      - src
      - tests
      - jest.config.ts
      - tsconfig.test.json
      - tsconfig.json
      - examples
    generates:
      - coverage
    cmds:
      - node_modules/.bin/jest --coverage

includes:
  npm: ./build.npm.yaml
