
tasks:
  rebuild:
    description: build typescript
    deps: [ npm:install ]
    image: node:14.16.0
    src:
      - src
      - tsconfig.json
    generates:
      - dist
    cmds:
      - rm -r dist || true
      - node_modules/.bin/tsc

  build:
    description: build typescript
    deps: [npm:install]
    image: node:14.16.0
    src:
      - src
      - tsconfig.json
    generates:
      - dist
    cmds:
      - node_modules/.bin/tsc

  format:
    description: lint fix and prettier
    image: node:14.16.0
    deps: [npm:install]
    cmds:
      - node_modules/.bin/prettier -w src/** tests/**
      - node_modules/.bin/eslint . --ext .ts --fix
    src:
      - src
      - tests
      - .eslintignore
      - .eslintrc
      - .prettierrc

  lint:
    description: lint source code
    image: node:14.16.0
    deps: [npm:install]
    src:
      - src
      - tests
      - .eslintignore
      - .eslintrc
    cmds:
      - node_modules/.bin/eslint . --ext .ts

  prettier:
    description: format source code
    image: node:14.16.0
    deps: [npm:install]
    src:
      - src
      - tests
      - .prettierrc
    cmds:
      - node_modules/.bin/prettier -w src/** tests/**

  test:
    description: test code
    deps: [npm:install]
    src:
      - src
      - tests
      - jest.config.ts
      - tsconfig.test.json
      - tsconfig.json
      - examples
    generates:
      - coverage
    cmds:
      - node_modules/.bin/jest --coverage

  publish:minor:
    description: publish npm package with minor version
    deps: [rebuild]
    cmds:
      - npm version minor
      - npm publish

  publish:patch:
    description: publish npm package with patch version
    deps: [rebuild]
    cmds:
      - npm version patch
      - npm publish

includes:
  npm: ./build.npm.yaml
