services:
  postgres:
    image: postgres:12-alpine
    ports: [5432]
    envs:
      POSTGRES_USER: api
      POSTGRES_DB: api
      POSTGRES_PASSWORD: 123456
    volumes:
      - "postgres-db:/var/lib/postgresql/data"
    healthcheck:
      cmd: "pg_isready -U postgres"

tasks:
  example:service:
    needs: [postgres]
    image: postgres:12-alpine
    envs:
      PGPASSWORD: 123456
    cmds:
      - psql -h postgres -U api -d api -c "CREATE TABLE test (id uuid primary key)"

  example:
    description: clean example
    generates:
      - node_modules
    src:
      - package.json
    cmds:
      - npm install

  docker:example:
    description: clean example
    image: node:16.6.0-alpine
    mounts:
      - $PWD/.npm:/.npm
      - $PWD/.config:/.config
    generates:
      - node_modules
    src:
      - package.json
    cmds:
      - npm install
