tasks:
  example:
    description: clean example
    image: node:14.16.0
    mounts:
      - $PWD/.npm:/.npm
      - $PWD/.config:/.config
    generates:
      - node_modules
    cmds:
      - npm install hammerkit
