services:
  api:
    image: node:16.6.0-alpine
    deps: [install]
    labels:
      task: dev
    ports:
      - 8080
    src:
      - src/*.js
    cmd: node src/index.js

tasks:
  install:
    image: node:16.6.0-alpine
    mounts:
      - $PWD/.npm:/.npm
      - $PWD/.config:/.config
    cmds:
      - npm install
    generates:
      - node_modules
      - package-lock.json
    src:
      - package.json

  work:
    image: node:16.6.0-alpine
    deps: [install]
    src:
      - src/work.js
    cmds:
      - node src/work.js
