tasks:
  install:
    cmds:
      - npm install
    generates:
      - node_modules
    src:
      - package.json
      - package-lock.json

  api:
    deps: [install]
    src:
      - src
      - tsconfig.json
    cmds:
      - node -r ts-node/register src/index.ts
