services:
  postgres:
    image: postgres:12
    envs:
      POSTGRES_USER: api
      POSTGRES_DB: api
      POSTGRES_PASSWORD: 123456
    healthcheck:
      cmd: "pg_isready -U postgres"
    ports:
      - 5432

tasks:
  install:
    image: node:14.16.0
    mounts:
      - $PWD/.npm:/.npm
      - $PWD/.config:/.config
    src:
      - package.json
      - package-lock.json
    generates:
      - node_modules
    cmds:
      - npm install

  api:
    image: node:14.16.0
    deps: [install]
    needs: [postgres]
    src:
      - src/index.ts
    cmds:
      - node -r ts-node/register src/index.ts
