tasks:
  example:
    description: install npm packages
    image: node:16.6.0-alpine
    mounts:
      - npm:/.npm
    src:
      - package.json
      - package-lock.json
    generates:
      - node_modules
    cmds:
      - npm ci
