tasks:
  build:
    image: node:14.16.0
    deps: [npm:install, a:build]
    src:
      - tsconfig.json
      - src
    cmds:
      - node_modules/.bin/tsc
    generates:
      - dist

references:
  a: ../a/build.yaml

includes:
  npm: ../../build.npm.yaml
