tasks:
  example_docker:
    image: alpine:latest
    description: sleep
    cmds:
      - echo start
      - sleep 120
      - sleep 120
      - echo end

  example:
    description: sleep
    cmds:
      - echo start
      - sleep 120
      - sleep 120
      - echo end
