envs:
  KUBECTL_VERSION: latest

tasks:
  get-pods:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest #bitnami/kubectl:latest
    mounts:
      - $PWD/.kube/config:/.kube/config
      - $PWD/.config/gcloud:/.config/gcloud
    cmds:
      - kubectl get pod
