tasks:
  example:
    description: run ref task
    deps: [foo:bar]
    cmds:
      - echo foo

  name:example:
    description: name example
    cmds:
      - echo name example

includes:
  foo: ./foo
