tasks:
  base_env:
    envs:
      NAME: base

  base_dep:
    deps: [base_env]

  extend_dep:
    extend: base_dep
    deps: [extend_env]

  base_container_task:
    image: alpine:latest
    envs:
      NAME: base
    cmds:
      - echo base

  extend_container_task:
    extend: base_container_task
    envs:
      NAME: override

  extend_env:
    extend: base_env
    envs:
      KEEP: value
