services:
  api:
    image: node:16.6.0-alpine
    deps: [npm:install]
    needs:
      - service: base:postgres
        name: postgres
    ports:
      - 3020:3000
    labels:
      task: dev
      project: b
    mounts:
      - server.js
      - config.json
    cmd: node server.js
    healthcheck:
      cmd: "wget -qO- http://localhost:3000"

includes:
  npm: ../../.npm.hammerkit.yaml

references:
  base: ../..
