name: master
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm test
