name: master
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ env.GITHUB_REF }}-${{ env.GITHUB_SHA }}
          path: ~/.cache
          restore-keys: |
            - ${{ env.GITHUB_REF }}-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: no0dles/hammerkit-github-action@v1.3
      - run: ls -la ~/.cache
      - run: hammerkit restore ~/.cache
      - run: ls -la
      - run: hammerkit lint
      - run: hammerkit prettier
      - run: hammerkit build
      - run: hammerkit store ~/.cache
      - run: ls -la ~/.cache
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: no0dles/hammerkit-github-action@v1.3
      - run: hammerkit test
      - name: upload coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
