name: master
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          key: build-${{ github.ref }}-${{ github.sha }}
          path: ~/.cache
          restore-keys: |
            build-${{ github.ref }}-
      - uses: no0dles/hammerkit-github-action@v1.3
      - run: hammerkit restore ~/.cache
      - run: hammerkit lint
      - run: hammerkit prettier
      - run: hammerkit build
      - run: hammerkit store ~/.cache
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: no0dles/hammerkit-github-action@v1.3
      - run: docker buildx create --use
      - run: hammerkit build:docker
        env:
          IMAGE_TAG: latest
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: test-${{ github.ref }}-${{ github.sha }}
          path: ~/.cache
          restore-keys: |
            test-${{ github.ref }}-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: no0dles/hammerkit-github-action@v1.3
      - run: hammerkit restore ~/.cache
      - run: hammerkit test
      - run: hammerkit store ~/.cache
      - name: upload coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

  publish-docker:
    runs-on: ubuntu-18.04
    needs: [test, docker]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: no0dles/hammerkit-github-action@v1.3
      - name: Version
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF:11}
      - run: hammerkit publish:docker --verbose
        env:
          IMAGE_TAG: ${{ steps.version.outputs.VERSION }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  publish-npm:
    runs-on: ubuntu-18.04
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: no0dles/hammerkit-github-action@v1.3
      - run: hammerkit publish:npm --verbose
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
