name: master
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}-${{ github.sha	 }}
          path: ~/.cache
          restore-keys: |
            - ${{ github.ref }}-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: no0dles/hammerkit-github-action@v1.3
      - run: hammerkit restore ~/.cache --verbose
      - run: hammerkit lint --verbose
      - run: hammerkit prettier --verbose
      - run: hammerkit build --verbose
      - run: hammerkit store ~/.cache --verbose
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: no0dles/hammerkit-github-action@v1.3
      - run: hammerkit test
      - name: upload coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
