name: test
on:
  push:
    branches:
      - '**'
jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
      - name: Install npm packages
        run: npm ci
      - name: Run tests
        run: node_modules/.bin/jest --runInBand
        timeout-minutes: 15
        env:
          VERBOSE: true
          CLUSTER_NAME: kind-chart-testing
      - name: Archive test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: console-log
          path: |
            logs
      - name: Upload coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
      - name: Install npm packages
        run: npm ci
      - name: Run tests
        run: node_modules/.bin/jest --runInBand
        timeout-minutes: 15
        env:
          VERBOSE: true

  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-12 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
      - name: Install npm packages
        run: npm ci
      - name: Run tests
        run: node_modules/.bin/jest --runInBand
        timeout-minutes: 15
        env:
          VERBOSE: true
      - name: Archive test artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: console-log
          path: |
            logs
