name: test
on:
  push:
    branches:
      - '**'
jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - run: kubectl config get-contexts
      - name: Install npm packages
        run: npm ci
      - name: Run tests
        run: node_modules/.bin/jest --runInBand
        timeout-minutes: 15
        env:
          VERBOSE: true
          LINUX_CONTAINERS: true
          CLUSTER_NAME: minikube
      - name: Archive test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: console-log-${{ matrix.os }}
          path: |
            logs
      - name: Upload coverage
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
