name: test
on:
  push:
    branches:
      - '**'
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install npm packages
        run: npm ci
      - name: Run tests
        run: npm test
        timeout-minutes: 10
        env:
          VERBOSE: true
      - name: Archive test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: console-log
          path: |
            logs
      - name: Upload coverage
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
